knowvi/urls.py
from django.conf.urls import patterns, url
from knowvi import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^about', views.about, name='about'),
        url(r'^category/(?P<category_name_url>\w+)/$', views.category,
            name='category'),
        url(r'^add_category/$', views.add_category, name='add_category'),
        url(r'^category/(?P<category_name_url>\w+)/add_page/$',
            views.add_page, name='add_page'),
        url(r'^register/$', views.register, name='register'), 
        url(r'^login/$', views.user_login, name='login'),
        url(r'^restricted/', views.restricted, name='restricted'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^search/$', views.search, name='search'),
        url(r'^goto/$', views.track_url, name='track_url'),
        url(r'^contact/$', views.contact, name='contact'),
)

knowvi_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'knowvi_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Enables the admin
    url(r'^admin/', include(admin.site.urls)),

    url(r'^knowvi/', include('knowvi.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
            'serve',
            {'document_root' : settings.MEDIA_ROOT}),  )

knowvi/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

class PageAdmin(admin.ModelAdmin):
    list_display = ('title', 'category', 'url')

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful
    def __unicode__(self):
        return self.user.username

knowvi/forms.py
from django import forms
from knowvi.models import Page, Category, UserProfile
from django.contrib.auth.models import User
from django import forms

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, 
            help_text="Please enter the category name.") 
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
            help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://', prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
        
        return cleaned_data

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them...
        # Here, we are hiding the foreign key.
        fields = ('title', 'url', 'views')

class UserForm(forms.ModelForm):
    username = forms.CharField(help_text="Please enter a username.")
    email = forms.CharField(help_text="Please enter your email.")
    password = forms.CharField(widget=forms.PasswordInput(), 
            help_text="Please enter a password.")

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(help_text="Please enter your website.", 
            required=False)
    picture = forms.ImageField(help_text="Select a profile image to upload.",
            required=False)

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=30)
    email = forms.EmailField(required=False)
    message = forms.CharField(widget=forms.Textarea(attrs={'cols': '25',
        'rows': '5'}))

knowvi/views.py
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# import Models
from knowvi.models import Category, Page

# import Forms
from knowvi.forms import CategoryForm
from knowvi.forms import PageForm
from knowvi.forms import UserForm, UserProfileForm
from knowvi.forms import ContactForm

# Checking date and time
from datetime import datetime

# Sending mail
from django.core.mail import send_mail

def encode_url(str):
    return str.replace(' ', '_')

def decode_url(str):
    return str.replace('_', ' ')

def index(request):
    # Request context of the request
    # The context contains information such as the client's machine
    context = RequestContext(request)
    context_dict = {}

    # Retrieve top 5 categories ranked by views, descending
    category_list = Category.objects.order_by('-views')[:5]
    context_dict['categories'] = category_list

    page_list = Page.objects.order_by('-views')[:5]
    context_dict['pages'] = page_list

    for category in category_list:
        category.url = encode_url(category.name);
    
    response = render_to_response('knowvi/index.html', context_dict, context)

    if request.session.get('last_visit'):
        # The session has a value for the last visit
        last_visit_time = request.session.get('last_visit')
        visits = request.session.get('visits', 0)

        if (datetime.now() - datetime.strptime(last_visit_time[:7],
            "%Y-%m-%d %H:%M:%S")).days > 0:
            request.session['visits'] = visits + 1
            request.session['last_visit'] = str(datetime.now())
        else:
            # The get returns None, and the session does not have a value for
            # the last visit.
            request.session['last_visit'] = str(datetime.now())
            request.session['visits'] = 1

    # Return response back to the user, updating any cookies that need changed.
    return response

def about(request):
    context = RequestContext(request)

    context_dict = {'boldmessage': "I am bold font from the context"}

    if request.session.get('visits'):
        count = request.session.get('visits')
    else:
        count = 0

    context_dict['visits'] = count

    return render_to_response('knowvi/about.html', context_dict, context)

def category(request, category_name_url):
    context = RequestContext(request)
    category_name = decode_url(category_name_url)
    context_dict = {'category_name': category_name}
    context_dict['category_name_url'] = category_name_url

    try:
        category = Category.objects.get(name=category_name)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        pass

    return render_to_response('knowvi/category.html', context_dict, context)

def add_category(request):
    # Get the context from the request.
    context = RequestContext(request)

    context_dict = {}

    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)

            # Now call the index() view.
            # The user will be shown the homepage.
            return index(request)
        else:
            # The supplied form contained errors - just print them to the terminal.
            print form.errors
    else:
        # If the request was not a POST, display the form to enter details.
        form = CategoryForm()

    context_dict['form'] = form
    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render_to_response('knowvi/add_category.html', context_dict, context)

def add_page(request, category_name_url):
    context = RequestContext(request)
    context_dict = {}

    category_name = decode_url(category_name_url)
    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            # This time we cannot commit straight away
            # Not all fields are automatically populated
            page = form.save(commit=False)

            # Retrieve the associated Category object so we can add it.
            # Wrap the code in a try block - check if the category actually exists!
            try:
                cat = Category.objects.get(name=category_name)
                page.category = cat
            except Category.DoesNotExist:
                # If we get here, the category does not exist.
                # Go back and render the add category form as a way of saying the 
                # the category does not exist.
                return render_to_response('knowvi/add_category.html', {}, context)

            # Also, create a default value for the number of views
            page.views = 0

            # With this, we can save our new model instance
            page.save()

            # Now that the page is saved, display the category instead
            return category(request, category_name_url)
        else:
            print form.errors
    else:
        form = PageForm()

    context_dict['category_name_url'] = category_name_url
    context_dict['category_name'] = category_name
    context_dict['form'] = form

    return render_to_response('knowvi/add_page.html',
                              context_dict, context)

def register(request):
    # Like before, get the request's context/
    context = RequestContext(request)
    context_dict = {}

    # A boolean value for telling the template whether the registration was 
    # successful. Set to False intially. Code changes value to True when 
    # registration succeeds
    registered = False

    # If it's a HTTP POST, we're interested in processing form data
    if request.method == 'POST':
        # Attempt to grab information from the raw form information
        # Note that we make use of both UserForm and UserProfileForm
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database
            user = user_form.save()

            # Now we has the password with the set_password method
            #Once hashed, we can update the user object
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance
            # Since we need to set the user attribute ourselves, we set commit=False
            # This delays saving the model until we're ready to avoid integrity problems
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put in in the
            # UserProfile model
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance
            profile.save()

            # Update our variable to tell the template registration was successful
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal
        # They'll also be shown to the user
        else:
            print user_form.errors, profile_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances
    # These forms will be blank, ready for user input
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context_dict['user_form'] = user_form
    context_dict['profile_form'] = profile_form
    context_dict['registered'] = registered

    # Render the template depending on the context
    return render_to_response('knowvi/register.html', context_dict, context)

def user_login(request):
    # Like before, obtain the context for the user's request
    context = RequestContext(request)
    context_dict = {}

    # If the request is a HTTP POST, try to pull out the relevant information
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        username = request.POST['username']
        password = request.POST['password']

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is retruned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no
        # user with matching credentials was found
        if user:
            # Is the account active? It could haev been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/knowvi/')
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your Knowvi account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:

templates/knowvi/about.html
{% extends 'knowvi/base.html' %}

{% load static %}

{% block title %}About{% endblock %}

{% block body_block %}

<div class="jumbotron">
    
    <h1>About</h1>
    <p><strong>Knowvi</strong> is a collection of links that I have found
    over the years.</p>
    <p>It is made using Django 1.6 with Bootstrap 3.1 styling.</p> 

</div>

<hr>
<footer>
    <div class="container">
        <p>&copy; 2014, Knowvi. </p>
    </div>
</footer>

{% endblock %}

templates/knowvi/add_category.html
{% extends 'knowvi/base.html' %}

{% block title %}Add a Category{% endblock %}

{% block body_block %}
<div class="jumbotron">
    <h1>Add a Category</h1>
    <div class="container">
        <form id="category_form" method="post"
            action="/knowvi/add_category/">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_txt }}
                {{ field }}
            {% endfor %}

            <br />
            <br />
            <button class="btn btn-primary" type="submit" name="submit"
                >Create Category</button>
        </form>
    </div>
</div>
{% endblock %}

templates/knowvi/add_page.html
{% extends 'knowvi/base.html' %}

{% block title %}Add a Page{% endblock %}

{% block body_block %}
<div class="jumbotron">
    <h1>Add a Page</h1>
    <div class="container">
        <form id="page_form" method="post"
            action="/knowvi/category/{{category_name_url}}/add_page/">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_txt }}
                {{ field }}
            {% endfor %}

            <br />
            <br />
            <button class="btn btn-primary" type="submit" name="submit"
                >Create Page</button>
        </form>
    </div>
</div>
{% endblock %}

templates/knowvi/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A curated collection of links">
    <meta name="author" content="Jackson Wu">
    <!--
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">
    -->

    <title>Knowvi</title>

    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet">
  </head>

<body>

    <!-- Top bar -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/knowvi/">Knowvi</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/knowvi/contact/">Submit</a></li>
      </ul>
      <form class="navbar-form navbar-right" action="/knowvi/search/">
          <input type="text" name="q" class="form-control" 
          placeholder="Search...">
      </form>
    </div>
  </div>
</div>



<div class="container-fluid">
  <div class="row">

      <!-- Sidebar -->
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
          <li {% if request.path == "/knowvi/" %} class="active"{% endif %}>
          <a href="/knowvi/">Home</a></li>
          <li {% if request.path == '/knowvi/about/' %}class="active"{% endif %}>
          <a href="/knowvi/about/">About</a></li>
      </ul>
      <ul class="nav nav-sidebar">

          <li {% if request.path == "/knowvi/category/Collections/" %}
          class="active"{% endif %}><a href="/knowvi/category/Collections/"
              >Collections</a></li>

          <li {% if request.path == "/knowvi/category/Computer_Science/" %}
              class="active"{% endif %}><a href="/knowvi/category/Computer_Science/"
              >Computer Science</a></li>

          <li {% if request.path == "/knowvi/category/Dictionary/" %}
          class="active"{% endif %}><a href="/knowvi/category/Dictionary/"
              >Dictionary</a></li>

          <li {% if request.path == "/knowvi/category/Languages/" %}
          class="active"{% endif %}><a href="/knowvi/category/Languages/"
              >Languages</a></li>

          <li {% if request.path == "/knowvi/category/Physics/" %}
          class="active"{% endif %}><a href="/knowvi/category/Physics/"
              >Physics</a></li>

      </ul>
    </div>

    <!-- Main content -->
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        {% block body_block %}
        {% endblock %}
    </div>

    </div> <!-- row -->
</div> <!-- container-fluid -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static "js/jquery-2.1.1.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>

</body>
</html>

templates/knowvi/base2.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet"
    media="screen">
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet">

    <title>Knowvi {% block title %}- A curated collection of links
        {% endblock %}</title>
</head>

<body>

    <!-- top bar -->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" 
                data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/knowvi/">Knowvi</a>
        </div> <!-- container-fluid -->    

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li class="navbar-text">Welcome, {{ user.username }}!</li>
                <li><a href="/knowvi/logout/">Logout</a></li>
                {% else %}
                <li><a href="/knowvi/register/">Register</a></li>
                <li><a href="/knowvi/login/">Login</a></li>
                {% endif %}
            </ul>
            <ul class="nav">
                {% if user.is_authenticated %}
                <li><a href="/knowvi/restricted/">Restricted Page</a></li>
                <li><a href="/knowvi/add_category/">Add a New Category</a></li>
                {% endif %}
                <li><a href="/knowvi/about/">About</a></li>
                <!-- <li><a href="/knowvi/">Return to Index</a></li> -->
            </ul>
        </div> <!-- nav-collapse -->  
    </div> <!-- navbar-inner -->
</div> <!-- navbar -->

<hr>

<footer>
    <div class="container">
        <p>&copy; Knowvi: A curated collection of links 2014</p>
    </div>
</footer>

<script src="{% static "js/jquery-2.1.1.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
</body>

</html>

templates/knowvi/category.html
{% extends 'knowvi/base.html' %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
    <h1 class="page-header">{{ category_name }}</h1>

    {% if pages %}
    <ul>
        {% for page in pages %}
        <li>
            <a href="/knowvi/goto/?page_id={{page.id}}">{{page.title}}</a>
            {% if page.views > 1 %}
                - ({{ page.views }} views)
            {% elif page.views == 1 %}
                - ({{ page.views }} view)
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <strong>No pages currently in category.</strong>
    {% endif %}
{% endblock %}

templates/knowvi/category_list.html
<ul class="nav nav-list">
    {% if cat_list %}
        {% for cat in cat_list %}
            <li><a href="/knowvi/category/{{ cat.url }}">{{ cat.name }}</a></li>
        {% endfor %}
    {% else %}
        <li>No categories at present.</li>
    {% endif %}
</ul>

templates/knowvi/contact.html
{% extends 'knowvi/base.html' %}

{% block title %}Submit{% endblock %}

{% block body_block %}

<div class="jumbotron">
    <div class="container">
        <div class="col-lg-7 col-lg-offset-3">

            <h1 class="text-center">Contact Us</h1>

            {% if form.errors %}
                <p style="color: red;">
                    Please correct the error{{ form.errors|pluralize }} below.
                </p>
            {% endif %}

            <form class="text-center" id="contact_form" method="post" action="/knowvi/contact/">
                {% csrf_token %}

                <div class="field">
                    <label for="id_subject">Subject (required):</label>
                    {{ form.subject }}
                    {{ form.subject.errors }}
                </div>

                <div class="field">
                    <label for="id_email">&nbsp;&nbsp;E-mail (optional):</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>

                <div class="field">
                    <label for="id_message">Message:</label>
                    {{ form.message.errors }}
                    <p>{{ form.message }}</p>
                </div>

                <button class="btn btn-primary" type="submit">Submit</button>
            </form>


        </div> <!-- col-lg-6 -->
    </div>
</div>

{% endblock %}

templates/knowvi/index.html
{% extends 'knowvi/base.html' %}

{% block body_block %}

<div class="jumbotron">
    <h1>Welcome to Knowvi</h1>
    <p>A collection of informative, interesting, and obscure links.</p>
</div>

<div class="row">

    <div class="col-xs-6">
        <h2 class="sub-header">Newly Added Categories</h2>
        <ul>
            <li><a href="/knowvi/category/Collections/"
                >Collections</a></li>
            <li><a href="/knowvi/category/Computer_Science/"
                >Computer Science</a></li>
            <li><a href="/knowvi/category/Dictionary/"
                >Dictionary</a></li>
            <li><a href="/knowvi/category/Languages/"
                >Languages</a></li>
            <li><a href="/knowvi/category/Physics/"
                >Physics</a></li>
        </ul>
    </div>

    <div class="col-xs-5">
        <h2 class="sub-header">Top Five Pages</h2>
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href="{{ page.url}}">{{ page.title }}</a>
            - {{ page.category }} ({{ page.views }} view(s))</li>
            {% endfor %}
        </ul> 
        {% else %}
        <strong>No pages at present.</strong>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/knowvi/login.html
{% extends 'knowvi/base.html' %}

{% block title %}Login{% endblock %}

{% block body_block %}

<div class="jumbotron">

    <div class="container" id="wrap">
        <div class="col-lg-6 col-lg-offset-3">

            <h1>Login</h1>
            
            <form id="login_form" method="post" action="/knowvi/login/">
                <h2>Please sign in</h2>
                {% csrf_token %}

                {% if bad_details %}
                <p><strong>Your username and/or password were incorrect!</strong></p>
                {% elif disabled_account %}
                <p><strong>Your Knowvi account is currently disabled; we can't log
                    you in.</strong></p>
                {% endif %}

                <input type="text" class="form-control input-lg" 
                placeholder="Username" name="username" value="" size="50" />
                <br />
                <input type="password" class="form-control input-lg" 
                placeholder="Password" name="password" value="" size="50" />
                <br />
            
                <button class="btn btn-primary" type="submit">Sign in</button>
            </form>

        </div> <!-- col-lg-6 -->
    </div> <!-- container -->
</div>

{% endblock %}

templates/knowvi/register.html
{% extends 'knowvi/base.html' %}

{% block title %}Register{% endblock %}

{% block body_block %}

<div class="jumbotron">

    <div class="container" id="wrap">
        <div class="col-lg-6 col-lg-offset-3">

            <h1>Register</h1>

            {% if registered %}
            <strong>Thank you for registering!</strong><br />
            {% else %}
            <strong>Register here!</strong><br />

            {% endif %}

            <form id="user_form" method="post"
                action="/knowvi/register/" enctype="multipart/form-data">

                {% csrf_token %}

                {% for field in user_form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                {% endfor %}

                {% for field in profile_form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                {% endfor %}

                <br />
                <button class="btn btn-primary" type="submit">Register</button>
            </form>

        </div>
    </div>
</div>

{% endblock %}

templates/knowvi/restricted.html
{% extends 'knowvi/base.html' %}

{% block title %}Restricted{% endblock %}

{% block body_block %}
    <h1 class="page-header">Restricted Page</h1>
    This is a restricted page that only users can access.
{% endblock %}

templates/knowvi/search.html
{% extends 'knowvi/base.html' %}

{% block title %}Search{% endblock %}

{% block body_block %}
<div class="jumbotron">
    <h1 class="page-header">Search</h1>

    <div class="container">
        <p>Search Results: {{ query }}</p>
        {% if pages %}
        <ul>
            {% for page in pages %}
                <li><a href="/knowvi/goto/?page_id={{page.id}}"
                    >{{page.title}}</a>
                {% if page.views > 1 %}
                    - ({{ page.views }} views)
                {% elif page.views == 1 %}
                    - ({{ page.views }} view)
                </li>
                {% endif %}
            {% endfor %}
        </ul>
        {% else %}
            <p>No matches found.</p>
        {% endif %}
    </div> <!-- container -->

</div>

{% endblock %}